"""
export_utils.py
===============
Render structured minutes into Markdown, plain text, DOCX, CSV and JSON.

The renderers all consume the same normalised dict produced by
``llm._normalise``, so adding a new export format never requires touching the
extraction logic.
"""

from __future__ import annotations

import csv
import io
import json
from datetime import datetime
from typing import Any

# --------------------------------------------------------------------------- #
# Markdown
# --------------------------------------------------------------------------- #


def to_markdown(d: dict[str, Any]) -> str:
    """Render minutes as GitHub-flavoured Markdown."""
    L: list[str] = []
    add = L.append

    add(f"# {d.get('title', 'Meeting Minutes')}")
    add("")

    meta = [
        ("Date", d.get("meeting_date", "Not stated")),
        ("Duration", d.get("duration", "Not stated")),
        ("Generated", datetime.now().strftime("%d %B %Y, %H:%M")),
    ]
    for key, value in meta:
        add(f"**{key}:** {value}  ")
    add("")

    if d.get("attendees"):
        add(f"**Attendees:** {', '.join(d['attendees'])}  ")
    if d.get("absentees"):
        add(f"**Apologies:** {', '.join(d['absentees'])}  ")
    add("")
    add("---")
    add("")

    if d.get("executive_summary"):
        add("## Executive Summary")
        add("")
        add(d["executive_summary"])
        add("")

    if d.get("agenda_items"):
        add("## Agenda")
        add("")
        for i, item in enumerate(d["agenda_items"], 1):
            add(f"{i}. {item}")
        add("")

    if d.get("discussion_points"):
        add("## Discussion")
        add("")
        for block in d["discussion_points"]:
            add(f"### {block.get('topic', 'Discussion')}")
            add("")
            for point in block.get("points", []):
                add(f"- {point}")
            add("")

    if d.get("decisions"):
        add("## Decisions")
        add("")
        for i, dec in enumerate(d["decisions"], 1):
            add(f"{i}. **{dec.get('decision', '')}**")
            if dec.get("rationale"):
                add(f"   - *Rationale:* {dec['rationale']}")
            if dec.get("owner") and dec["owner"] != "Unassigned":
                add(f"   - *Owner:* {dec['owner']}")
        add("")

    if d.get("action_items"):
        add("## Action Items")
        add("")
        add("| # | Task | Owner | Deadline | Priority |")
        add("|---|------|-------|----------|----------|")
        for i, a in enumerate(d["action_items"], 1):
            task = str(a.get("task", "")).replace("|", "\\|")
            add(
                f"| {i} | {task} | {a.get('owner', 'Unassigned')} | "
                f"{a.get('deadline', '—')} | {a.get('priority', 'Medium')} |"
            )
        add("")

    if d.get("risks_and_blockers"):
        add("## Risks & Blockers")
        add("")
        for r in d["risks_and_blockers"]:
            line = f"- **{r.get('item', '')}**"
            if r.get("impact"):
                line += f" — {r['impact']}"
            if r.get("owner") and r["owner"] != "Unassigned":
                line += f" *(owner: {r['owner']})*"
            add(line)
        add("")

    if d.get("open_questions"):
        add("## Open Questions")
        add("")
        for q in d["open_questions"]:
            add(f"- {q}")
        add("")

    if d.get("next_meeting") and d["next_meeting"] != "Not scheduled":
        add("## Next Meeting")
        add("")
        add(d["next_meeting"])
        add("")

    add("---")
    add("")
    add("*Generated by AI Meeting Minutes Generator*")

    return "\n".join(L)


# --------------------------------------------------------------------------- #
# Plain text
# --------------------------------------------------------------------------- #


def to_text(d: dict[str, Any]) -> str:
    """Render minutes as clean plain text suitable for pasting into email."""
    W = 74
    L: list[str] = []
    add = L.append

    def rule(char: str = "=") -> None:
        add(char * W)

    def section(name: str) -> None:
        add("")
        add(name.upper())
        rule("-")

    rule()
    add(str(d.get("title", "Meeting Minutes")).upper().center(W))
    rule()
    add("")
    add(f"Date      : {d.get('meeting_date', 'Not stated')}")
    add(f"Duration  : {d.get('duration', 'Not stated')}")
    add(f"Generated : {datetime.now().strftime('%d %B %Y, %H:%M')}")

    if d.get("attendees"):
        add("")
        add("Attendees :")
        for person in d["attendees"]:
            add(f"  - {person}")
    if d.get("absentees"):
        add("Apologies :")
        for person in d["absentees"]:
            add(f"  - {person}")

    if d.get("executive_summary"):
        section("Executive Summary")
        for line in _wrap(d["executive_summary"], W):
            add(line)

    if d.get("agenda_items"):
        section("Agenda")
        for i, item in enumerate(d["agenda_items"], 1):
            add(f"{i}. {item}")

    if d.get("discussion_points"):
        section("Discussion")
        for block in d["discussion_points"]:
            add("")
            add(f"  {block.get('topic', 'Discussion')}")
            for point in block.get("points", []):
                for j, line in enumerate(_wrap(point, W - 6)):
                    add(("    - " if j == 0 else "      ") + line)

    if d.get("decisions"):
        section("Decisions")
        for i, dec in enumerate(d["decisions"], 1):
            for j, line in enumerate(_wrap(dec.get("decision", ""), W - 5)):
                add((f"{i}. " if j == 0 else "   ") + line)
            if dec.get("rationale"):
                for line in _wrap(f"Rationale: {dec['rationale']}", W - 7):
                    add("     " + line)
            if dec.get("owner") and dec["owner"] != "Unassigned":
                add(f"     Owner: {dec['owner']}")

    if d.get("action_items"):
        section("Action Items")
        for i, a in enumerate(d["action_items"], 1):
            for j, line in enumerate(_wrap(a.get("task", ""), W - 5)):
                add((f"{i}. " if j == 0 else "   ") + line)
            add(
                f"     Owner: {a.get('owner', 'Unassigned')}"
                f"  |  Due: {a.get('deadline', '—')}"
                f"  |  Priority: {a.get('priority', 'Medium')}"
            )

    if d.get("risks_and_blockers"):
        section("Risks & Blockers")
        for r in d["risks_and_blockers"]:
            for j, line in enumerate(_wrap(r.get("item", ""), W - 6)):
                add(("  ! " if j == 0 else "    ") + line)
            if r.get("impact"):
                for line in _wrap(f"Impact: {r['impact']}", W - 8):
                    add("      " + line)

    if d.get("open_questions"):
        section("Open Questions")
        for q in d["open_questions"]:
            for j, line in enumerate(_wrap(q, W - 6)):
                add(("  ? " if j == 0 else "    ") + line)

    if d.get("next_meeting") and d["next_meeting"] != "Not scheduled":
        section("Next Meeting")
        add(f"  {d['next_meeting']}")

    add("")
    rule()
    add("Generated by AI Meeting Minutes Generator".center(W))
    rule()

    return "\n".join(L)


def _wrap(text: str, width: int) -> list[str]:
    """Simple greedy word wrap."""
    words = str(text).split()
    if not words:
        return [""]
    lines: list[str] = []
    current = ""
    for word in words:
        if len(current) + len(word) + 1 <= width:
            current = f"{current} {word}".strip()
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


# --------------------------------------------------------------------------- #
# DOCX
# --------------------------------------------------------------------------- #


def to_docx(d: dict[str, Any]) -> bytes:
    """Render minutes as a formatted Word document."""
    from docx import Document
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt, RGBColor

    INK = RGBColor(0x0B, 0x10, 0x20)
    VIOLET = RGBColor(0x6D, 0x5E, 0xF8)
    SLATE = RGBColor(0x64, 0x74, 0x8B)

    doc = Document()

    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(10.5)

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run(str(d.get("title", "Meeting Minutes")))
    run.font.size = Pt(22)
    run.font.bold = True
    run.font.color.rgb = INK

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = sub.add_run(
        f"{d.get('meeting_date', 'Not stated')}  •  "
        f"Duration: {d.get('duration', 'Not stated')}"
    )
    sub_run.font.size = Pt(9.5)
    sub_run.font.color.rgb = SLATE

    doc.add_paragraph("─" * 58).alignment = WD_ALIGN_PARAGRAPH.CENTER

    def heading(text: str) -> None:
        para = doc.add_paragraph()
        para.paragraph_format.space_before = Pt(14)
        para.paragraph_format.space_after = Pt(6)
        run = para.add_run(text.upper())
        run.font.size = Pt(10)
        run.font.bold = True
        run.font.color.rgb = VIOLET

    if d.get("attendees"):
        heading("Attendees")
        doc.add_paragraph(", ".join(d["attendees"]))
    if d.get("absentees"):
        heading("Apologies")
        doc.add_paragraph(", ".join(d["absentees"]))

    if d.get("executive_summary"):
        heading("Executive Summary")
        para = doc.add_paragraph(d["executive_summary"])
        para.paragraph_format.space_after = Pt(8)

    if d.get("agenda_items"):
        heading("Agenda")
        for item in d["agenda_items"]:
            doc.add_paragraph(str(item), style="List Number")

    if d.get("discussion_points"):
        heading("Discussion")
        for block in d["discussion_points"]:
            para = doc.add_paragraph()
            run = para.add_run(str(block.get("topic", "Discussion")))
            run.font.bold = True
            run.font.size = Pt(11)
            for point in block.get("points", []):
                doc.add_paragraph(str(point), style="List Bullet")

    if d.get("decisions"):
        heading("Decisions")
        for i, dec in enumerate(d["decisions"], 1):
            para = doc.add_paragraph()
            num = para.add_run(f"{i}. ")
            num.font.bold = True
            text = para.add_run(str(dec.get("decision", "")))
            text.font.bold = True
            if dec.get("rationale"):
                why = doc.add_paragraph(f"Rationale: {dec['rationale']}")
                why.paragraph_format.left_indent = Pt(20)
                why.runs[0].font.size = Pt(9.5)
                why.runs[0].font.italic = True
                why.runs[0].font.color.rgb = SLATE
            if dec.get("owner") and dec["owner"] != "Unassigned":
                owner = doc.add_paragraph(f"Owner: {dec['owner']}")
                owner.paragraph_format.left_indent = Pt(20)
                owner.runs[0].font.size = Pt(9.5)
                owner.runs[0].font.color.rgb = SLATE

    if d.get("action_items"):
        heading("Action Items")
        table = doc.add_table(rows=1, cols=4)
        table.style = "Light Grid Accent 1"
        headers = table.rows[0].cells
        for idx, label in enumerate(["Task", "Owner", "Deadline", "Priority"]):
            headers[idx].text = label
            for para in headers[idx].paragraphs:
                for run in para.runs:
                    run.font.bold = True
                    run.font.size = Pt(9.5)
        for a in d["action_items"]:
            cells = table.add_row().cells
            cells[0].text = str(a.get("task", ""))
            cells[1].text = str(a.get("owner", "Unassigned"))
            cells[2].text = str(a.get("deadline", "—"))
            cells[3].text = str(a.get("priority", "Medium"))
            for cell in cells:
                for para in cell.paragraphs:
                    for run in para.runs:
                        run.font.size = Pt(9.5)

    if d.get("risks_and_blockers"):
        heading("Risks & Blockers")
        for r in d["risks_and_blockers"]:
            text = str(r.get("item", ""))
            if r.get("impact"):
                text += f" — {r['impact']}"
            if r.get("owner") and r["owner"] != "Unassigned":
                text += f" (owner: {r['owner']})"
            doc.add_paragraph(text, style="List Bullet")

    if d.get("open_questions"):
        heading("Open Questions")
        for q in d["open_questions"]:
            doc.add_paragraph(str(q), style="List Bullet")

    if d.get("next_meeting") and d["next_meeting"] != "Not scheduled":
        heading("Next Meeting")
        doc.add_paragraph(str(d["next_meeting"]))

    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.paragraph_format.space_before = Pt(20)
    frun = footer.add_run(
        f"Generated by AI Meeting Minutes Generator  •  "
        f"{datetime.now().strftime('%d %B %Y, %H:%M')}"
    )
    frun.font.size = Pt(8)
    frun.font.color.rgb = SLATE

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


# --------------------------------------------------------------------------- #
# CSV / JSON
# --------------------------------------------------------------------------- #


def actions_to_csv(d: dict[str, Any]) -> str:
    """Export just the action items — importable into Excel, Jira, Trello."""
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(["#", "Task", "Owner", "Deadline", "Priority", "Meeting", "Date"])
    for i, a in enumerate(d.get("action_items", []), 1):
        writer.writerow(
            [
                i,
                a.get("task", ""),
                a.get("owner", "Unassigned"),
                a.get("deadline", ""),
                a.get("priority", "Medium"),
                d.get("title", ""),
                d.get("meeting_date", ""),
            ]
        )
    return buffer.getvalue()


def to_json(d: dict[str, Any]) -> str:
    """Pretty-printed JSON — useful for showing the structured extraction."""
    return json.dumps(d, indent=2, ensure_ascii=False)


def safe_filename(title: str, extension: str) -> str:
    """Build a filesystem-safe download filename."""
    base = "".join(ch if ch.isalnum() or ch in " -_" else "" for ch in str(title))
    base = "_".join(base.split())[:50] or "meeting_minutes"
    return f"{base}_{datetime.now().strftime('%Y%m%d')}.{extension}"
